name: QQPlayer v3.x
on:
  workflow_dispatch:

jobs:
  v4_0:
    name: v4.0
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Exe
        shell: cmd
        run: |
          v3.x.exe

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: v3.x
          path: v3.x.txt
